package org.example.app.viewmodel

import androidx.lifecycle.LiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.asLiveData
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import org.example.app.data.TaskEntity
import org.example.app.data.TasksRepository

/**
 * ViewModel exposing tasks list and actions for UI.
 */
class TasksViewModel(
    private val repository: TasksRepository
) : ViewModel() {

    val tasks: LiveData<List<TaskEntity>> = repository.observeTasks().asLiveData()

    init {
        seedIfEmpty()
    }

    private fun seedIfEmpty() {
        viewModelScope.launch(Dispatchers.IO) {
            if (repository.count() == 0) {
                val now = System.currentTimeMillis()
                repository.insertAll(
                    listOf(
                        TaskEntity(
                            title = "Welcome to Task Organizer",
                            description = "Tap + to add tasks, swipe to delete with undo, or use ⋮ to edit/delete.",
                            isCompleted = false,
                            createdAt = now,
                            updatedAt = now,
                            dueDate = null
                        ),
                        TaskEntity(
                            title = "Try marking a task complete",
                            description = "Use the checkbox to toggle completion.",
                            isCompleted = false,
                            createdAt = now,
                            updatedAt = now,
                            dueDate = null
                        )
                    )
                )
            }
        }
    }

    fun addTask(title: String, description: String?, dueDate: Long?) {
        viewModelScope.launch(Dispatchers.IO) {
            val now = System.currentTimeMillis()
            repository.insert(
                TaskEntity(
                    title = title.trim(),
                    description = description?.trim()?.takeIf { it.isNotBlank() },
                    isCompleted = false,
                    createdAt = now,
                    updatedAt = now,
                    dueDate = dueDate
                )
            )
        }
    }

    fun updateTask(existing: TaskEntity, title: String, description: String?, dueDate: Long?) {
        viewModelScope.launch(Dispatchers.IO) {
            val now = System.currentTimeMillis()
            repository.update(
                existing.copy(
                    title = title.trim(),
                    description = description?.trim()?.takeIf { it.isNotBlank() },
                    updatedAt = now,
                    dueDate = dueDate
                )
            )
        }
    }

    fun setCompleted(task: TaskEntity, completed: Boolean) {
        viewModelScope.launch(Dispatchers.IO) {
            val now = System.currentTimeMillis()
            repository.update(task.copy(isCompleted = completed, updatedAt = now))
        }
    }

    fun deleteTask(task: TaskEntity) {
        viewModelScope.launch(Dispatchers.IO) {
            repository.delete(task)
        }
    }

    // PUBLIC_INTERFACE
    fun clearCompletedTasks() {
        /**
         * Deletes all completed tasks.
         */
        viewModelScope.launch(Dispatchers.IO) {
            repository.deleteCompleted()
        }
    }

    /**
     * Used for Snackbar "Undo" after swipe/delete.
     */
    fun restoreTask(task: TaskEntity) {
        viewModelScope.launch(Dispatchers.IO) {
            // Re-insert. If the id was autogenerated before, Room will replace if same PK exists,
            // otherwise insert new row.
            repository.insert(task.copy(updatedAt = System.currentTimeMillis()))
        }
    }

    suspend fun getTaskById(id: Long): TaskEntity? = repository.getTask(id)
}
